POWR-2974 Remove batch alias generation after group_path update
eGovPDX/portlandor pull request #1659
Opened 2020-11-17 18:09 UTC by kxwang

2020-11-18 00:29 UTC, joshuami requested changes
I think we can remove this TODO: `    // <TODO:>LOW PRIORITY: rEGenerate URL aliases for group action links using group path (ie. /bds/content, /bds/members)</TODO:>
`.

Seems like that is covered by extended path aliases now. 

Does the code really need the force group path update? Saving the group doesn't do the trick? I'm just wondering if we could drop that code as well. 🤔

2020-11-18 17:34 UTC, kxwang commented
Removed the entire hook. Please review. Please note that content without short title will get the bad URL again after bulk generation.

> I think we can remove this TODO: ` // <TODO:>LOW PRIORITY: rEGenerate URL aliases for group action links using group path (ie. /bds/content, /bds/members)</TODO:>`.
> 
> Seems like that is covered by extended path aliases now.
> 
> Does the code really need the force group path update? Saving the group doesn't do the trick? I'm just wondering if we could drop that code as well. 🤔

2020-11-18 19:07 UTC, joshuami commented
Thanks for the update. We should be good to go on all pages and services with short titles. We manually added those for all published content. All unpublished content has the bad paths, but should get fixed as editors try to edit the content and are required to add a short title.

2020-11-19 22:43 UTC, joshuami submitted a review, later dismissed

2020-11-24 00:21 UTC, joshuami approved these changes

2020-11-24 00:21 UTC, merged