POWR-3873 Update PHP to 8.0 in Pantheon and Lando
eGovPDX/portlandor pull request #2233
Opened 2022-03-28 21:13 UTC by kxwang

2022-03-31 21:58 UTC, RichardDavies commented on .circleci/config.yml
> -          - source-v1-{{ .Branch }}-
Why did you remove the fallback keys?

2022-03-31 22:01 UTC, RichardDavies commented on .circleci/config.yml
> -          - source-v1-{{ .Branch }}-
Their documentation examples include fallback keys just like these so I'm curious why you removed them. https://circleci.com/docs/2.0/caching/

2022-03-31 23:31 UTC, RichardDavies requested changes

2022-03-31 23:31 UTC, RichardDavies commented on .circleci/config.yml
> -          - source-v1-
You missed restoring this cache key.

2022-03-31 23:43 UTC, kxwang commented on .circleci/config.yml
> -          - source-v1-
Good catch!

2022-04-01 00:04 UTC, RichardDavies approved these changes

2022-04-01 23:04 UTC, joshuami approved these changes

2022-04-01 23:04 UTC, merged